spring.application.name=taskhive

# DATABASE
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/taskhive_db_josemoya?useSSL=false&serverTimezone=Europe/Madrid&allowPublicKeyRetrieval=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:taskhive_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:TaskHive123!}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=true

# THYMELEAF
spring.thymeleaf.cache=false

# H2 DESACTIVADA
spring.h2.console.enabled=false

# INIT SQL
spring.sql.init.mode=never

# SERVER
server.port=${PORT:8080}